### ISSUE TITLE
how to pack ram bundle

### ISSUE THREAD

**Issue by zhuangxuan** [kirillzyusko/react-native-bundle-splitter#13]
I have integrate this lib into my project, but I can not find pack ram bundle command.

when i use plain bundle, I use this command 'npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/index.android.bundle --assets-dest ./android'.  when I use this lib with ram bundle ,which command should i use.  thank you very much

**Comment by kirillzyusko** [comment]
Hi @zhuangxuan 
You should use `npx react-native ram-bundle` command. You can read more [here](https://github.com/react-native-community/cli/blob/master/docs/commands.md#ram-bundle).

Let me know, whether I answered on your question or not :)

**Comment by zhuangxuan** [comment]
very thanks, that is what I want.
I have another question ,Could you help me?
I try to avoid phone start white screen, What can I do for app. 
Could you give me a advise ？

**Comment by kirillzyusko** [comment]
@zhuangxuan you can not avoid it. It's special initialization stage. And all applications have such stage. It's called Splash Screen.
You can modify it as you wish (put on this screen logo/text). For doing this you may use react-native-splash-screen, react-native-bootsplash libraries.
But you can not avoid it.

**Comment by zhuangxuan** [comment]
@kirillzyusko  very thanks,  your advise is good.  I will try to reduce white screen time.  Have a good time.

**Comment by kirillzyusko** [comment]
@zhuangxuan you too. Feel free to create new issues. I will close this one.
