### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by pontusab** [kirillzyusko/react-native-bundle-splitter#2]
Thanks for a great lib!

We have one small issue with this running in yarn workspaces, if it's loaded from the root node_modules (without nohoist) the library outputs the error "require is not a function".

Moving the lib to the subfolder ie nohoist it works as expected.

**Comment by pontusab** [comment]
After investigation running with no hoist the app crashes in production build but works in dev mode

**Comment by kirillzyusko** [comment]
Hi, @pontusab 
Thank you for the issue :)
Could you please create a small project/reproducable demo?
And also, please, say, which version of the library do you use?
In fact I fixed similar error in 1.0.5

**Comment by pontusab** [comment]
Hey man! I use the latest version of this library, I will create a repo for you!

**Comment by kirillzyusko** [comment]
@pontusab Amazing! Thank you😎
