### ISSUE TITLE
can supply a register by 'group' way example

### ISSUE THREAD

**Issue by seenyea** [kirillzyusko/react-native-bundle-splitter#20]
**Is your feature request related to a problem? Please describe.**
supply a register by 'group' way example

**Comment by kirillzyusko** [comment]
@seenyea I think I already wrote about [it](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/async-loading#group-of-screens), isn't?

**Comment by seenyea** [comment]
I think a working example, not a doc example

**Comment by kirillzyusko** [comment]
@seenyea ah, yes. It's on my roadmap in v2. I'm writing snacks, so you can try it straight in browser :)

**Comment by kirillzyusko** [comment]
Closed due to https://github.com/kirillzyusko/react-native-bundle-splitter/issues/23
