### ISSUE TITLE
can add a tab navigation example

### ISSUE THREAD

**Issue by seenyea** [kirillzyusko/react-native-bundle-splitter#21]
**Is your feature request related to a problem? Please describe.**
can add a tab navigation example

**Comment by kirillzyusko** [comment]
@seenyea what you mean by tabs? There are variety of ways how it can be implemented using various libraries, such as: `react-native-tab-view`, `@react-navigation/bottom-tabs` and so on. What exactly you want?

**Comment by seenyea** [comment]
I mean, a demo of using tabs with react-native-bundle-splitter

**Comment by kirillzyusko** [comment]
@seenyea should it be with `@react-navigation/bottom-tabs`?

In fact I'm writing right now a lot of snacks/demos, just thinking which of them I should include in final docs.

**Comment by kirillzyusko** [comment]
Closed due to https://github.com/kirillzyusko/react-native-bundle-splitter/issues/23
