### ISSUE TITLE
Support for RN 0.64.0 (inline requires enabled by default)

### ISSUE THREAD

**Issue by sandeshnaroju** [kirillzyusko/react-native-bundle-splitter#24]
Thanks for the library. Recently RN 0.64.0 has inline requires enabled by default. so is this supported with 0.64.0?

**Comment by kirillzyusko** [comment]
Hi @sandeshnaroju 

Yes, previously **inline requires** was experimental feature (but it was used widely in many projects, including Facebook app).

Now it's enabled by default. You still can use this library with 0.64. There is no any breaking changes for that :)

Did I answer on your question?
