### ISSUE TITLE
feat - ForwardRef in OptimizedComponent

### ISSUE THREAD

**Issue by alessioemireni** [kirillzyusko/react-native-bundle-splitter#26]
**Is your feature request related to a problem? Please describe.**
When a Child Component is wrapped with `register` method, the parent component can't invoke its method with ref and the app crashes.

**Describe the solution you'd like**
In OptimizedComponent is possible to use the [ForwardRef React API](https://reactjs.org/docs/forwarding-refs.html).

I've forked your library and commited the right solution --> https://github.com/alessioemireni/react-native-bundle-splitter/commit/d2c78df24803e6083c81d835cfc368b8516c12bc.

If it's ok, I will open a PR.

**Additional context**
![Screenshot 2021-04-16 at 14 13 06](https://user-images.githubusercontent.com/9269526/115373018-bd391580-a1cb-11eb-90ed-7e7be545fe91.png)

**Comment by kirillzyusko** [comment]
Hi @alessioemireni 

Yes, please, open a PR.

Also, that would be nice to provide some code examples, when this bug (crash) appears.

And also, if it's possible, please, don't use `any` type in your PR :)

Once it will be done, I will be glad to merge it and publish a new version!

**Comment by alessioemireni** [comment]
Hi @kirillzyusko.

Here you can find a demo with the reproducible issue --> https://github.com/alessioemireni/react-native-bundle-splitter-example/tree/mobile/forward-ref-crash

1. Open the app
2. Click on Details
3. On page details click on Button "Press me"
4. The app crash

If you comment the `register` in index.ts of `MyComponents` component and uncomment the `export` everything works fine.

Also I have corrected the type any with a type generic.

**Comment by kirillzyusko** [comment]
@alessioemireni Yes. I was thinking about this usage. But just wanted to check it (that's why I asked you to give an example).

Thank you for your PR! I will publish new version soon.
