### ISSUE TITLE
Add to docs: how is this different from RN built in RAM bundles?

### ISSUE THREAD

**Issue by JulianKingman** [kirillzyusko/react-native-bundle-splitter#28]
**Is your feature request related to a problem? Please describe.**
React Native lays out how to implement RAM bundles: https://reactnative.dev/docs/ram-bundles-inline-requires

**Describe the solution you'd like**
What does this package do differently? What's the same? Why use or not use this project?

**Comment by kirillzyusko** [comment]
Hi @JulianKingman 

The explanation is below:

```
This package is built on top of RAM bundles. It allows you to:
- avoid boilerplate code (you don't need to write code as per react-native docs - you can simply wrap your component into `register` function);
- use preload API (when you can load screens in advance and the transition to them will be as if the entire bundle was loaded at once);
- and has web support.
```

Where you would like to see it on a website? On which page?

**Comment by JulianKingman** [comment]
I would put it in the getting started section of the documentation:
https://kirillzyusko.github.io/react-native-bundle-splitter/docs/getting-started

>  ## What does this package do?
> This package is built on top of RAM bundles. In addition to the base functionality provided by React Native, it allows you to:
>  - Avoid boilerplate... etc

I would also love to know how this package relates to Hermes (if you know), since this package conflicts with it (RAM bundles conflicts with it), and solves related problems (Hermes chunks byte code into separate bundles).

**Comment by kirillzyusko** [comment]
@JulianKingman yes, hermes is using similar mechanism. If you are using Hermes, you don't need to enable RAM bundles :)
