### ISSUE TITLE
React Navigation - missing header and error

### ISSUE THREAD

**Issue by hypnocill** [kirillzyusko/react-native-bundle-splitter#32]
I implemented the react-native-bundle-splitter using the guide in https://kirillzyusko.github.io/react-native-bundle-splitter/docs/navigation

It seems to improve the startup time indeed but the header of the navigation is not visible and when I try to navigate to another screen from this navigator, I get "No 'routes' found in navigation state" error:

I'm using react-navigation 4.0.10

Here's an example of how my stack navigator looks like. The header is defined in ../components/Screen which is loaded at first. I get the error when I try to navigate to ScreenTwo

export const MyNavigator = createStackNavigator(
    {
      Screen: {
        screen: register({ loader: () => import('../components/Screen') }),
        navigationOptions: {
          headerBackTitle: null,
        },
      },
      ScreenTwo: {
        screen: register({ loader: () => import('../components/ScreenTwo') }),
        navigationOptions: {
          headerBackTitle: null,
        },
      }
    },
    {
      headerMode: 'float',
    }
  );
}

MyNavigator.navigationOptions = ({ navigation }) => {
    return {
      header: null,
    };
  };

**Comment by hypnocill** [comment]
Thank you for your response!

From my example code above - I moved the static 'navigationOptions' from inside  ../components/Screen to the MyNavigator (as per the documentation you just linked) but I still don't get the header rendered.
A console.log inside the register's static returned 'navigationOptions' is never executed.

And I keep getting the "No 'routes' found in navigation state" error" when I try to navigate from Screen to ScreenTwo.

Unfortunately I can't record a demo with the current codebase due to privacy but if I don't find a way to make it work, I'll try to create a demo from scratch since I really do need that startup time boost.

**Comment by kirillzyusko** [comment]
@hypnocill I don't see any drawbacks🙂

But what is the difference between this code and the code that you've attached in the first message? For me both of them look identical to each other... And I'm curious what has changed and why it's working now🤔

I'm pretty sure I'm missing something important 😅

**Comment by hypnocill** [comment]
Yeah, this issue seems like exactly what I encountered with "no routes in navigation state" error.

Thanks for the detailed explanation
