### ISSUE TITLE
Dynamic setting of navigationOptions.

### ISSUE THREAD

**Issue by vidsag** [kirillzyusko/react-native-bundle-splitter#4]
Hi, 
I am trying to set the `navigationOptions` for the screen.
The current implementation is,
`    static navigationOptions = ({ navigation }) => {
        const params = navigation.state.params || {};
        let title = params.title ? params.title : "";
         return {
          title: title,
          headerLeft: (
            <HeaderIcon
              onPress={params.goBack}
              iconName="arrow-back"
              theme="light"
            />
          ),
          ...NavigationHelper.getHeaderStyles("light", true)
        };
    };`

This is the current implementation when using the library

`register({ require: () => require('./screens/TopicScreen'),
        static: { 
            navigationOptions: { 
                title: "TopicName",
                headerLeft: (
                  <HeaderIcon
                    // onPress={goBack}
                    iconName="arrow-back"
                    theme="light"
                  />
                ),
                ...NavigationHelper.getHeaderStyles("light", true)         
               } 
        } 
     }),`

My question is how can I get the `TopicName` here for the title as it is set using `setParams` in the screen.

**Comment by kirillzyusko** [comment]
Hey, @vidsag 
It should work:
```
register({ 
  require: () => require('./screens/TopicScreen'), 
  static: { 
    navigationOptions: ({ navigation }) => {
      // your implementation from first code snippet
    }
  },
}
```
Please, let me know, whether this works or not :)

**Comment by vidsag** [comment]
This works. Thanks!
