### ISSUE TITLE
Error - "Excessive number of pending callbacks"

### ISSUE THREAD

**Issue by pier-verdu** [kirillzyusko/react-native-bundle-splitter#7]
With:

- "react-native": "^0.63.2",
- "react-native-bundle-splitter": "^1.0.9",

Using like:

```ts
  <Stack.Navigator screenOptions={defaultNavigationOptions}>
              <Stack.Screen
                name={Home}
                component={register({
                  require: () => require('./AuthHomeContainer'),
                })}
                options={{ headerShown: false, animationEnabled: false }}
              />
              <Stack.Screen
                name={Login}
                component={register({
                  require: () => require('../../Login'),
                })}
                options={{ headerShown: false }}
              />
              <Stack.Screen
                name={Logout}
                component={register({
                  require: () => require('./Logout'),
                })}
                options={({ route }) => {
                  return getNavigationOptions(route, true, true, true);
                }}
              />
```

The app freeze during the navigation (after 4 screens) and I have:

>ExceptionsManager.js:179 Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"7238":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7380":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"7476":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"9204":{"module":"ReanimatedModule","method":"getValue"},"9213":{"module":"ReanimatedModule","method":"getValue"},"9249":{"module":"ReanimatedModule","method":"getValue"},"9277":{"module":"ReanimatedModule","method":"getValue"},"9294":{"module":"ReanimatedModule","method":"getValue"},"9300":{"module":"ReanimatedModule","method":"getValue"},"9322":{"module":"ReanimatedModule","method":"getValue"},"9331":{"module":"ReanimatedModule","method":"getValue"},"9337":{"module":"ReanimatedModule","method":"getValue"},"9347":{"module":"ReanimatedModule","method":"getValue"},"9382":{"module":"ReanimatedModule","method":"getValue"},"9400":{"module":"ReanimatedModule","method":"getValue"},"9453":{"module":"ReanimatedModule","method":"getValue"},"9469":{"module":"ReanimatedModule","method":"getValue"},"9474":{"module":"ReanimatedModule","method":"getValue"},"9487":{"module":"ReanimatedModule","method":"getValue"},"9494":{"module":"ReanimatedModule","method":"getValue"},"9502":{"module":"ReanimatedModule","method":"getValue"},"9513":{"module":"ReanimatedModule","method":"getValue"},"9516":{"module":"ReanimatedModule","method":"getValue"},"9524":{"module":"ReanimatedModule","method":"getValue"},"9532":{"module":"ReanimatedModule","method":"getValue"},"9535":{"module":"ReanimatedModule","method":"getValue"},"9538":{"module":"ReanimatedModule","method":"getValue"},"9543":{"module":"ReanimatedModule","method":"getValue"},"9546":{"module":"ReanimatedModule","method":"getValue"},"9558":{"module":"ReanimatedModule","method":"getValue"},"9585":{"module":"ReanimatedModule","method":"getValue"},"9593":{"module":"ReanimatedModule","method":"getValue"},"9600":{"module":"ReanimatedModule","method":"getValue"},"9619":{"module":"ReanimatedModule","method":"getValue"},"9639":{"module":"ReanimatedModule","method":"getValue"},"10765":{"module":"ReanimatedModule","method":"getValue"},"10774":{"module":"ReanimatedModule","method":"getValue"},"10810":{"module":"ReanimatedModule","method":"getValue"},"10838":{"module":"ReanimatedModule","method":"getValue"},"10855":{"module":"ReanimatedModule","method":"getValue"},"10861":{"module":"ReanimatedModule","method":"getValue"},"10883":{"module":"ReanimatedModule","method":"getValue"},"10892":{"module":"ReanimatedModule","method":"getValue"},"10898":{"module":"ReanimatedModule","method":"getValue"},"10908":{"module":"ReanimatedModule","method":"getValue"},"10943":{"module":"ReanimatedModule","method":"getValue"},"10961":{"module":"ReanimatedModule","method":"getValue"},"11014":{"module":"ReanimatedModule","method":"getValue"},"11030":{"module":"ReanimatedModule","method":"getValue"},"11035":{"module":"ReanimatedModule","method":"getValue"},"...(truncated keys)...":451}

**Comment by kirillzyusko** [comment]
Hi @Pierre-CLIND 
Maybe you missed a slash in `require: () => require('.Logout'),` ?
Shouldn't it be `require: () => require('./Logout'),` ?

**Comment by Pierre-CLIND** [comment]
Hi @kirillzyusko, no :/

I just rename the file name for the example,

**Comment by kirillzyusko** [comment]
@Pierre-CLIND Could you create small reproducible demo?
I don't see any issues in the code above. If I can look on entire project, maybe I can help to detect an issue.

**Comment by kirillzyusko** [comment]
@Pierre-CLIND hi!
Did you find a solution?
Also, could you please be sure, that `ROOT_FOLDER` in `metro.config.js` really refers to your root of the project?

**Comment by Pierre-CLIND** [comment]
Not really, sorry :/ I use Hermes now

**Comment by kirillzyusko** [comment]
Closed due to the inactivity.
